const autos = [
	{
		id: 1,
		nombre: 'Volkswagen Gol',
		marca: 'Volkswagen',
		modelo: 'Gol Trendline',
		precio: 17000,
		anio: 2020,
		categoria: 'auto',
		combustible: 'Nafta',
		descripcion: 'Volkswagen Gol Trend',
		img: './img/golTrend.jpeg',
		oferta: true,
	},

	{
		id: 2,
		nombre: 'Volkswagen Gol Sedan',
		marca: 'Volkswagen',
		modelo: 'Gol Sedan',
		precio: 18500,
		anio: 2021,
		categoria: 'auto',
		combustible: 'Nafta',
		descripcion: 'Volkswagen Gol Sedan',
		img: './img/golSedan.jpeg',
		oferta: false,
	},
	{
		id: 3,
		nombre: 'Volkswagen Saveiro',
		marca: 'Volkswagen',
		modelo: 'Saveiro G6',
		precio: 16500,
		anio: 2021,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Volkswagen Saveiro G6',
		img: './img/saveiroCS.jpeg',
		oferta: true,
	},
	{
		id: 4,
		nombre: 'Volkswagen Saveiro Cross',
		marca: 'Volkswagen',
		modelo: 'Saveiro Cross',
		precio: 21500,
		anio: 2021,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Volkswagen Saveiro Cross',
		img: './img/saveiroCross.jpeg',
		oferta: false,
	},
	{
		id: 5,
		nombre: 'Volkswagen Vento',
		marca: 'Volkswagen',
		modelo: 'Vento Confortline',
		precio: 31500,
		anio: 2022,
		categoria: 'auto',
		combustible: 'Nafta',
		descripcion: 'Volkswagen Vento Confortline',
		img: './img/vento.jpeg',
		oferta: false,
	},
	{
		id: 6,
		nombre: 'Volkswagen Polo',
		marca: 'Volkswagen',
		modelo: 'Polo Trendline',
		precio: 23000,
		anio: 2021,
		categoria: 'auto',
		combustible: 'Nafta',
		descripcion: 'Volkswagen Polo Trendline ',
		img: './img/polo.jpeg',
		oferta: false,
	},
	{
		id: 7,
		nombre: 'Fiat Strada',
		marca: 'Fiat',
		modelo: 'Strada Volcano',
		precio: 23500,
		anio: 2022,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Fiat Strada Volcano',
		img: './img/strada.jpeg',
		oferta: true,
	},
	{
		id: 8,
		nombre: 'Fiat Mobi',
		marca: 'Fiat',
		modelo: 'Mobi',
		precio: 12000,
		anio: 2020,
		categoria: 'auto',
		combustible: 'Nafta',
		descripcion: 'Fiat Mobi',
		img: './img/mobi.jpeg',
		oferta: true,
	},
	{
		id: 9,
		nombre: 'Fiat Fiorino',
		marca: 'Fiat',
		modelo: 'Fiorino',
		precio: 16000,
		anio: 2021,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Fiat Fiorino Furgon',
		img: './img/fiorino.jpeg',
		oferta: true,
	},
	{
		id: 10,
		nombre: 'Fiat Toro',
		marca: 'Fiat',
		modelo: 'Toro',
		precio: 30000,
		anio: 2022,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Fiat Toro',
		img: './img/toro.jpeg',
		oferta: false,
	},
	{
		id: 11,
		nombre: 'Renault Kwid',
		marca: 'Renault',
		modelo: 'Kwid',
		precio: 13000,
		anio: 2020,
		categoria: 'auto',
		combustible: 'Nafta',
		descripcion: 'Renault Kwid',
		img: './img/kwid.jpeg',
		oferta: true,
	},
	{
		id: 12,
		nombre: 'Renault Oroch',
		marca: 'Renault',
		modelo: 'Oroch',
		precio: 21000,
		anio: 2021,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Renault Oroch',
		img: './img/oroch.jpeg',
		oferta: false,
	},
	{
		id: 13,
		nombre: 'Renault Clio',
		marca: 'Renault',
		modelo: 'Clio',
		precio: 20000,
		anio: 2021,
		categoria: 'auto',
		combustible: 'Nafta',
		descripcion: 'Renault Clio',
		img: './img/clio.jpeg',
		oferta: false,
	},
	{
		id: 14,
		nombre: 'Renault Duster',
		marca: 'Renault',
		modelo: 'Duster',
		precio: 25000,
		anio: 2022,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Renault Duster Camioneta',
		img: './img/duster.jpg',
		oferta: false,
	},
	{
		id: 15,
		nombre: 'Renault Kangoo',
		marca: 'Renault',
		modelo: 'Kangoo',
		precio: 22000,
		anio: 2021,
		categoria: 'camioneta',
		combustible: 'Nafta',
		descripcion: 'Renault Kangoo Furgon',
		img: './img/kangoo.jpeg',
		oferta: false,
	},
];

const getCars = () => {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve(autos);
		}, 2000);
	});
};

export default getCars;
